/** @type {import('tailwindcss').Config} */
export default {
    content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
    theme: {
        extend: {
            fontFamily: {
                poppins: "'Poppins', sans-serif", // Adds a new `font-display` class
            },
        },
        animatedSettings: {
            animatedSpeed: 1000,
            heartBeatSpeed: 500,
            hingeSpeed: 2000,
            bounceInSpeed: 750,
            bounceOutSpeed: 750,
            animationDelaySpeed: 500,
            classes: [
                "bounce",
                "heartBeat",
                "flash",
                "pulse",
                "rubberBand",
                "shakeX",
                "shakeY",
                "headShake",
                "swing",
                "tada",
                "wobble",
                "jello",
                "heartBeat",
                "backInDown",
                "backInLeft",
                "backInRight",
                "backInUp",
                "backOutDown",
                "backOutLeft",
                "backOutRight",
                "backOutUp",
                "bounceIn",
                "bounceInDown",
                "bounceInLeft",
                "bounceInRight",
                "bounceInUp",
                "bounceOut",
                "bounceOutDown",
                "bounceOutLeft",
                "bounceOutRight",
                "bounceOutUp",
                "fadeIn",
                "fadeInDown",
                "fadeInDownBig",
                "fadeInLeft",
                "fadeInLeftBig",
                "fadeInRight",
                "fadeInRightBig",
                "fadeInUp",
                "fadeInUpBig",
                "fadeInTopLeft",
                "fadeInTopRight",
                "fadeInBottomLeft",
                "fadeInBottomRight",
                "fadeOut",
                "fadeOutDown",
                "fadeOutDownBig",
                "fadeOutLeft",
                "fadeOutLeftBig",
                "fadeOutRight",
                "fadeOutRightBig",
                "fadeOutUp",
                "fadeOutUpBig",
                "fadeOutTopLeft",
                "fadeOutTopRight",
                "fadeOutBottomRight",
                "fadeOutBottomLeft",
                "flip",
                "flipInX",
                "flipInY",
                "flipOutX",
                "flipOutY",
                "lightSpeedInRight",
                "lightSpeedInLeft",
                "lightSpeedOutRight",
                "lightSpeedOutLeft",
                "rotateIn",
                "rotateInDownLeft",
                "rotateInDownRight",
                "rotateInUpLeft",
                "rotateInUpRight",
                "rotateOut",
                "rotateOutDownLeft",
                "rotateOutDownRight",
                "rotateOutUpLeft",
                "rotateOutUpRight",
                "hinge",
                "jackInTheBox",
                "rollIn",
                "rollOut",
                "zoomIn",
                "zoomInDown",
                "zoomInLeft",
                "zoomInRight",
                "zoomInUp",
                "zoomOut",
                "zoomOutDown",
                "zoomOutLeft",
                "zoomOutRight",
                "zoomOutUp",
                "slideInDown",
                "slideInLeft",
                "slideInRight",
                "slideInUp",
                "slideOutDown",
                "slideOutLeft",
                "slideOutRight",
                "slideOutUp",
                "animate__delay-5s"
            ],
        },
    },
    plugins: [require("daisyui"), require("tailwindcss-animate")],
};
